#user
TEACHER_ROLE = "teacher"
STUDENT_ROLE = "student"
ADMIN_ROLE = "admin"

AVAILABLE_ROLES = [TEACHER_ROLE, STUDENT_ROLE]

#question
OBJECTIVE = "objective"
SUBJECTIVE = "subjective"

AVAILABLE_QUESTION_TYPES = [OBJECTIVE, SUBJECTIVE]

AVAILABLE_COURSES = %w{BCA BBA MCA MBA BCOM BA BE}