#user
TEACHER_ROLE = "teacher"
STUDENT_ROLE = "student"

AVAILABLE_ROLES = [TEACHER_ROLE, STUDENT_ROLE]

#question
OBJECTIVE = "objective"
SUBJECTIVE = "subjective"

AVAILABLE_QUESTION_TYPES = [OBJECTIVE, SUBJECTIVE]